name: Auto Blog Publisher with Indexing

on:
  schedule:
    - cron: '0 */3 * * *'
    - cron: '30 */3 * * *'
    - cron: '0 1,4,7,10,13,16,19,22 * * *'
    - cron: '30 1,4,7,10,13,16,19,22 * * *'
  workflow_dispatch: 

jobs:
  publish_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Determine Category based on Time
        id: set_category
        run: |
          if [ "${{ github.event.schedule }}" == '0 */3 * * *' ]; then
            echo "CATEGORY=Personal Finance" >> $GITHUB_ENV
          elif [ "${{ github.event.schedule }}" == '30 */3 * * *' ]; then
            echo "CATEGORY=Finance Book Summary" >> $GITHUB_ENV
          elif [ "${{ github.event.schedule }}" == '0 1,4,7,10,13,16,19,22 * * *' ]; then
            echo "CATEGORY=Finance News" >> $GITHUB_ENV
          elif [ "${{ github.event.schedule }}" == '30 1,4,7,10,13,16,19,22 * * *' ]; then
            echo "CATEGORY=World Viral News" >> $GITHUB_ENV
          else
            echo "CATEGORY=Personal Finance" >> $GITHUB_ENV
          fi

      - name: Run Python Script
        env:
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GEMINI_KEYS: ${{ secrets.GEMINI_KEYS }}
          BLOGGER_TOKEN_JSON: ${{ secrets.BLOGGER_TOKEN_JSON }}
          INDEXING_JSON: ${{ secrets.INDEXING_JSON }}
        run: python main.py
        
