name: Auto Blog Publisher with Interval

on:
  schedule:
    - cron: '0 */3 * * *'
    - cron: '30 */3 * * *'
    - cron: '0 1,4,7,10,13,16,19,22 * * *'
    - cron: '30 1,4,7,10,13,16,19,22 * * *'

  workflow_dispatch:

jobs:
  publish_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt google-genai google-api-python-client requests

      - name: Determine Category based on Scheduled Time
        id: set_category
        run: |
          EVENT_CRON="${{ github.event.schedule }}"
          
          if [ "$EVENT_CRON" == '0 */3 * * *' ]; then
            echo "CATEGORY=Personal Finance" >> $GITHUB_ENV
          elif [ "$EVENT_CRON" == '30 */3 * * *' ]; then
            echo "CATEGORY=Finance Book Summary" >> $GITHUB_ENV
          elif [ "$EVENT_CRON" == '0 1,4,7,10,13,16,19,22 * * *' ]; then
            echo "CATEGORY=Finance News" >> $GITHUB_ENV
          elif [ "$EVENT_CRON" == '30 1,4,7,10,13,16,19,22 * * *' ]; then
            echo "CATEGORY=World Viral News" >> $GITHUB_ENV
          else
            echo "CATEGORY=Personal Finance" >> $GITHUB_ENV
          fi

      - name: Run Python Script
        env:
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GEMINI_KEYS: ${{ secrets.GEMINI_KEYS }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          INDEXING_JSON: ${{ secrets.INDEXING_JSON }}
          BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
          BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
          BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
          CATEGORY: ${{ env.CATEGORY }}
        run: python main.py
        
